config/routes.rb
Rails.application.routes.draw do
  resources :interestings
  root "interestings#index"
end

app/models/interesting.rb
class Interesting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interestings_controller.rb
class InterestingsController < ApplicationController
  def index
    @interestings = Interesting.all.order(created_at: "DESC")
    render :index
  end

  def new
    @interesting = Interesting.new
    render :new
  end

  def create
    Interesting.create(params.require(:interesting).permit([:title, :description, :user_name]))
    redirect_to interestings_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interestings_helper.rb
module InterestingsHelper
end

app/views/interestings/index.html.erb
<div>
  <a href="/interestings/new" class="btn btn-danger">Add</a>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Interesting title</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @interestings.each do |interesting| %>
      <tr>
        <td><i class="fa fa-user"></i><%= interesting.user_name %></td>
        <td><%= interesting.title %></td>
        <td><%= interesting.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/interestings/new.html.erb
<h3>Add interesting</h3>
<%= form_for :interesting, url: interestings_path, method: :post do |f|%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :user_name, class: "form-control", placeholder: "John Doe" %>
  </div>
  <div class="form-group">
    <%= f.label :interesting_title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Programming your own drone" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Buy a drone..." %>
  </div>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whiteboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="logo-container container">
  <%= image_tag "bitsource-logo", class: "bitsource-logo"%>
</div>
<div class="container">
  <%= yield %>
</div>
</body>
</html>